version: "3.5"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - target: 80
        published: 5200
        protocol: tcp
        mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    volumes:
      - type: volume
        source: pgadmin-data
        target: /var/lib/pgadmin  

  db:
    image: postgres:11.7
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      POSTGRES_USER: pgAdminUser
      POSTGRES_PASSWORD: s0m3_Th1ng
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

volumes:
  postgres-data:
  pgadmin-data:
