version: '3.1'

services:

    kibana:
        image: kibana
        ports:
            - 5601:5601
        environment:            
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
            - elasticsearch

    elasticsearch:
        image: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300